@startuml C4. Контекст

title C4. Контекст

!include <C4/C4_Container>

Person(admin, "Администратор", "Модерирует учётные записи, концерты и отзывы пользователей")
Person(organizer, "Организатор", "Размещает и редактирует концерты, управляет продажами")
Person(user, "Пользователь", "Бронирует места, посещает концерты, оставляет отзывы")

System(concert_system, "Система поиска и резервирования билетов на концерты")
Rel(admin, concert_system, "Контролирует контент")
Rel(organizer, concert_system, "Размещает концерты")
Rel(user, concert_system, "Бронирует места")

System_Ext(payment_system, "Платежная система", "Предоставление возможности оплаты")
System_Ext(map_system, "Система картографии", "Предоставление адреса по координатам")
System_Ext(email_system, "Email сервис", "Отправка уведомлений и билетов")
System_Ext(socials_system, "Социальные сети", "Продвижение мероприятий и взаимодействие с пользователями")

Rel(concert_system, payment_system, "Запрос на обработку платежа")
Rel(concert_system, map_system, "Запрашивает адреса концертных залов")
Rel(concert_system, email_system, "Передает информацию о концертах и билетах")
Rel(concert_system, socials_system, "Передает информацию о концертах")
@enduml