@startuml C4. Контейнеры
left to right direction

title C4. Контейнеры

!define C4P https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master
!$ICONURL = "https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v3.0.0/icons"
!include $ICONURL/devicons/react.puml
!include $ICONURL/devicons/postgresql.puml
!include $ICONURL/devicons/netmagazine.puml

!includeurl C4P/C4_Container.puml

Person(admin, "Администратор", "Модерирует учётные записи, концерты и отзывы пользователей")
Person(organizer, "Организатор", "Размещает и редактирует концерты, управляет продажами")
Person(user, "Пользователь", "Бронирует места, посещает концерты, оставляет отзывы")

System_Boundary(concert_system, "Система поиска и резервирования билетов на концерты") {
    Container(web_app, "Мультистраниченое веб-приложение", "React", "", $sprite="react")
    System_Boundary(services, "Сервисы") {
        Container(auth_service, "Шлюз авторизации и аутентификации", "C#, .NET", "", $sprite="netmagazine")
        Container(user_service, "Сервис пользователей", "C#, .NET", "", $sprite="netmagazine")
        Container(concert_service, "Сервис концертов", "C#, .NET", "", $sprite="netmagazine")
        Container(booking_service, "Сервис бронирования", "C#, .NET", "", $sprite="netmagazine")
        Container(payment_service, "Сервис платежей", "C#, .NET", "", $sprite="netmagazine")
        Container(notification_service, "Сервис уведомлений", "C#, .NET", "", $sprite="netmagazine")
        Container(analytics_service, "Сервис аналитики", "C#, .NET", "", $sprite="netmagazine")
        Container(social_integration_service, "Сервис интеграции с социальными сетями", "C#, .NET", "", $sprite="netmagazine")
    }
    Container(rabbitmq, "Шина событий", "RabbitMQ", "Обмен сообщениями между сервисами")
    Container(database, "База данных", "PostgreSQL", "", $sprite="postgresql")
}

System_Ext(payment_system, "Платежная система", "Предоставление возможности оплаты")
System_Ext(map_system, "Система картографии", "Предоставление адреса по координатам")
System_Ext(email_system, "Email сервис", "Отправка уведомлений и билетов")
System_Ext(socials_system, "Социальные сети", "Продвижение мероприятий и взаимодействие с пользователями")

Rel(admin, web_app, "Посещает", "HTTP")
Rel(organizer, web_app, "Посещает", "HTTP")
Rel(user, web_app, "Посещает", "HTTP")

Rel(services, database, "Читает/Пишет данные", "ADO.NET")
Rel(services, rabbitmq, "Создает/Читает события")

concert_service --> map_system : "Получает данные для отображения карты\n[REST API]\n(Сервис концертов)"
concert_service ---[hidden]---> map_system 
notification_service --> email_system : "API вызовы\n[REST API]\n(Сервис уведомлений)"
notification_service ---[hidden]---> email_system 
payment_service --> payment_system : "API вызовы\n[REST API]\n(Сервис платежей)"
payment_service ---[hidden]---> payment_system
social_integration_service --> socials_system : "API вызовы\n[REST API](Сервис интеграции с социальными сетями)"
social_integration_service ---[hidden]---> socials_system

Rel(web_app, services, "Создает/Читает события")

@enduml