@startuml C4. Компонент

title C4. Компонент

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!$ICONURL = "https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v3.0.0/icons"

Component(concertMicroservice, "Микросервис концертов", "C# .NET", $sprite="")

System_Boundary(libAcc, "API") {
    Component(concertController, "ConcertController", "C# .NET", " отвечает за обработку входящих запросов")
    Component(concertRepository, "ConcertRepository", "C# .NET", "отвечает за взаимодействие с базой данных для хранения и извлечения информации")
    Component(concertService, "ConcertService", "C# .NET", "включает в себя бизнес-логику")
    Rel(concertMicroservice, concertController, "")
    Rel(concertController, concertService, "")
    Rel(concertService, concertRepository, "")
}

System_Ext(eventManagementService, "EventManagmentService", "Управляет событиями, связанными с концертами")
Rel(concertService, eventManagementService, "")

System_Ext(notificationService, "NotificationService", "Отправляет уведомления пользователям о концертах")
Rel(concertService, notificationService, "")

System_Ext(map_system, "Система картографии", "Предоставление адреса по координатам")
Rel(concertService, map_system, "")

@enduml