@startuml Диаграмма состояний
title Диаграмма состояний
top to bottom direction
hide empty description
skinparam nodesep 65

[*] --> ПоискКонцертов : Нажатие "Поиск концертов"

ПоискКонцертов --> РезультатыПоиска : Выбор фильтров и поиск
РезультатыПоиска --> ДеталиКонцерта : Выбор конкретного концерта
ДеталиКонцерта --> СхемаЗала : Просмотр мест на схеме зала
ЗарезервированныеМеста --> Покупка : Оплата резерва
ЗарезервированныеМеста --> [*] : Отмена резерва

СхемаЗала --> Авторизован : Успешная авторизация
СхемаЗала --> Гость : Неуспешная авторизация
Авторизован --> ЗарезервированныеМеста : Выбор мест и резервирование
Авторизован --> Покупка : Выбор мест и переход к оплате
Гость --> [*] : Выход без авторизации

Покупка --> Успешно : Успешная оплата
Покупка --> [*] : Ошибка оплаты 

Успешно --> ИсторияПокупок : Запись в историю покупок
ИсторияПокупок --> [*] : Завершение сессии

Успешно --> ОставитьОтзыв : После завершения концерта
ОставитьОтзыв --> [*] : Отзыв оставлен


@enduml
