@startuml Диаграмма состояний
title Диаграмма состояний
top to bottom direction
hide empty description
skinparam nodesep 65

[*] --> Гость : Начало без авторизации
[*] --> Авторизован : Начало через авторизацию

Гость --> Авторизован : Успешная авторизация
Гость --> [*] : Выход без авторизации

Авторизован --> ПоискКонцертов : Нажатие "Поиск концертов"
Авторизован --> [*] : Выход из аккаунта

ПоискКонцертов --> РезультатыПоиска : Выбор фильтров и поиск
РезультатыПоиска --> ДеталиКонцерта : Выбор конкретного концерта
ДеталиКонцерта --> СхемаЗала : Просмотр мест на схеме зала
СхемаЗала --> ЗарезервированныеМеста : Выбор мест и резервирование
ЗарезервированныеМеста --> Покупка : Оплата резерва
ЗарезервированныеМеста --> [*] : Отмена резерва
СхемаЗала --> Покупка : Выбор мест и переход к оплате

Покупка --> Успешно : Успешная оплата
Покупка --> Неуспешно : Ошибка оплаты
Неуспешно --> СхемаЗала : Повтор выбора мест

Успешно --> ИсторияПокупок : Запись в историю покупок
ИсторияПокупок --> [*] : Завершение сессии

Успешно --> ОставитьОтзыв : После завершения концерта
ОставитьОтзыв --> [*] : Отзыв оставлен


@enduml
